### PR TITLE
Get labels from cds engine

### PR DESCRIPTION
**Pull request by swantrace**
Hi @preston,

Apologies for the delayed response. Here’s the current status of our project:

1. ESLint has been configured for the patient repository, and we're currently using Angular recommendations.
2. Temporarily, I have structured the data to represent the preview as an array of [string, boolean] pairs, where the string represents the label, and the boolean indicates permission (allow or deny).
3. For testing, I am using example-request-permit.json to verify if requests are sent correctly. The function that sends requests now accepts parameters specifying the category and its checked state. I am still determining what additional data (such as consent, patient, and organization details) might be needed to form the complete request body.
4. The system successfully retrieves responses from the post hook request. However, these responses are currently not utilized; I have temporarily assigned values to previewList to test if the popover can display dynamic content.

### CODE REVIEW

**Comment by preston** [comment]
Hi @swantrace , Let's review at our meeting tomorrow. Could you do a screenshare for that meeting?

**Comment by preston** [comment]
@swantrace The envsub thing isn't working at the moment as a .env file won't exist in the fully containerized production environment. All configuration is injected purely via environment variables. If you remove the "--env-file .env.local" part, though, it would work; you just have to `. .env.local` to load your personal config prior to startup. Maybe envsub has a way to not throw an error if the named .env.local file doesn't exist?

**Comment by preston** [comment]
Not sure if this helps, but note that I'm trying to pull as much common model code as possible into @asushares/core, e.g.
```typescript
import { NoConsentCard, PatientConsentHookRequest } from '@asushares/core';
```

If you have new data model types that will need to be resued in the provider app, which aren't dependent on either node core or Angular libraries, just let me know and I'll add it to the library.

**Comment by swantrace** [comment]
commits here have been merged in another PR

**Pull request closed without merging**
